<a href="https://colab.research.google.com/github/CharlesPrado23/Bootcamp_TurmaNoite/blob/main/Conteudo_02/Exerc%C3%ADcios_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
### Questão 1
### Use o método np.unique para retornar um array sem duplicatas

In [4]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [5]:
### Questão 2
### crie uma matriz (4,3) usando o método np.random.randn(x,y)

In [6]:
arr_ = np.array(np.random.randn(4,3))
arr_

array([[-1.37220216,  0.93132166, -1.2599473 ],
       [ 1.48800796, -0.6022291 , -0.42885353],
       [ 1.86775065,  0.89343693,  0.77851449],
       [ 0.55168599, -0.71939476, -2.27707809]])

In [7]:
### Questão 3 
### Retorne os elementos entre as linhas 2 e 3 ; e entre as colunas 1 e 2 
### Use o conceito de slice e armazene o resultada em outro array

In [8]:
arr_slice = arr_[1:3,:2]

In [9]:
### Questão 4 
### Calcule o valor médio da matriz da Questão 2 
### Calcule o valor médio da matriz da Questão 2 na direção horizontal
### Calcule o valor médio da matriz da Questão 2 na direção vertical

In [10]:
arr_.mean()

-0.012415603612490647

In [11]:
arr_.mean(axis=1)

array([-0.5669426 ,  0.15230845,  1.17990069, -0.81492895])

In [12]:
arr_.mean(axis=0)

array([ 0.63381061,  0.12578369, -0.79684111])

In [13]:
### Questão 5
### usando o método arange , crie um array com 50 posições 
### Modifique todos os valores para o valor igual a 1 
### Usando o método reshape crie uma matriz (10,50)

In [14]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
arr_q5 += 1

In [16]:
arr_q5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
arr_q5 = arr_q5/arr_q5
arr_q5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
arr_q5[arr_q5 >= 0] = 1

In [20]:
arr_q5

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [21]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
arr_q5[0:] = 1

In [23]:
arr_q5

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [24]:
np.full(50,5, dtype=str)

array(['5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5'], dtype='<U1')

In [25]:
### Usando o método reshape crie uma matriz (10,5)

In [26]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
arr_q5.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])